### ISSUE TITLE
Create HTML template for welcome email

### ISSUE THREAD

**Issue by Senjo903** [corecodeio/platform#6]
## Overview
- currently the function that sends the welcome message is already created, but for now it only sends a simple template:

```javascript
        const message = {
            from: nodeMailerConfig.auth.user,
            to: email,
            subject: 'Welcome to Core Code',
            html: `
            <p>hola ${first_name} ${last_name} ya esta registrado en nuestra plataforma<p>
            <a href="${clientConfig.student_url}/validate-email/${tokenEmail}">  
                <button>Validar Email</button>  
            </a>`
        };
```

- modify the html to send a template according to Core Code, and with an email validation button
## Additional Information:
- only the variables "first_name", "last_name" can be used and the button redirect url must stay the same 

```javascript
${clientConfig.student_url}/validate-email/${tokenEmail}
```

- the file "email.welcome.js" is located at:

```
/api/src/helpers/email.welcome.js
```

![Image](https://user-images.githubusercontent.com/82398006/229319992-193ebacc-8808-4abd-9a6f-f7ee5e9322d6.jpg)

## Additional Information:
- In figma you can find details of what is expected from the template.

[Here](https://www.figma.com/file/oxVOJVas6LrpcuIURCtzyp/Core-Code-Test-App?node-id=15%3A560&t=wn25KzFuopJQU2KH-1) Figma

**Comment by Aaryanpal** [comment]
@@Senjo903 …
I would like to work on this issue could u please assign tickets.
